/// <reference types="@pixi/filter-adjustment" />
/// <reference types="@pixi/filter-advanced-bloom" />
/// <reference types="@pixi/filter-ascii" />
/// <reference types="@pixi/filter-bevel" />
/// <reference types="@pixi/filter-bloom" />
/// <reference types="@pixi/filter-bulge-pinch" />
/// <reference types="@pixi/filter-color-map" />
/// <reference types="@pixi/filter-color-overlay" />
/// <reference types="@pixi/filter-color-replace" />
/// <reference types="@pixi/filter-convolution" />
/// <reference types="@pixi/filter-cross-hatch" />
/// <reference types="@pixi/filter-crt" />
/// <reference types="@pixi/filter-dot" />
/// <reference types="@pixi/filter-drop-shadow" />
/// <reference types="@pixi/filter-emboss" />
/// <reference types="@pixi/filter-glitch" />
/// <reference types="@pixi/filter-glow" />
/// <reference types="@pixi/filter-godray" />
/// <reference types="@pixi/filter-kawase-blur" />
/// <reference types="@pixi/filter-motion-blur" />
/// <reference types="@pixi/filter-multi-color-replace" />
/// <reference types="@pixi/filter-old-film" />
/// <reference types="@pixi/filter-outline" />
/// <reference types="@pixi/filter-pixelate" />
/// <reference types="@pixi/filter-radial-blur" />
/// <reference types="@pixi/filter-reflection" />
/// <reference types="@pixi/filter-rgb-split" />
/// <reference types="@pixi/filter-shockwave" />
/// <reference types="@pixi/filter-simple-lightmap" />
/// <reference types="@pixi/filter-tilt-shift" />
/// <reference types="@pixi/filter-twist" />
/// <reference types="@pixi/filter-zoom-blur" />

declare module "pixi-filters" {
    export * from "@pixi/filter-adjustment";
    export * from "@pixi/filter-advanced-bloom";
    export * from "@pixi/filter-ascii";
    export * from "@pixi/filter-bevel";
    export * from "@pixi/filter-bloom";
    export * from "@pixi/filter-bulge-pinch";
    export * from "@pixi/filter-color-map";
    export * from "@pixi/filter-color-overlay";
    export * from "@pixi/filter-color-replace";
    export * from "@pixi/filter-convolution";
    export * from "@pixi/filter-cross-hatch";
    export * from "@pixi/filter-crt";
    export * from "@pixi/filter-dot";
    export * from "@pixi/filter-drop-shadow";
    export * from "@pixi/filter-emboss";
    export * from "@pixi/filter-glitch";
    export * from "@pixi/filter-glow";
    export * from "@pixi/filter-godray";
    export * from "@pixi/filter-kawase-blur";
    export * from "@pixi/filter-motion-blur";
    export * from "@pixi/filter-multi-color-replace";
    export * from "@pixi/filter-old-film";
    export * from "@pixi/filter-outline";
    export * from "@pixi/filter-pixelate";
    export * from "@pixi/filter-radial-blur";
    export * from "@pixi/filter-reflection";
    export * from "@pixi/filter-rgb-split";
    export * from "@pixi/filter-shockwave";
    export * from "@pixi/filter-simple-lightmap";
    export * from "@pixi/filter-tilt-shift";
    export * from "@pixi/filter-twist";
    export * from "@pixi/filter-zoom-blur";
}
